sources:
  - name: "Open EPG"
    url: "https://www.open-epg.com/files/india1.xml.gz"
    active: true
    priority: 3
    offset: "+0530"
  - name: "Open EPG"
    url: "https://www.open-epg.com/files/india2.xml.gz"
    active: true
    priority: 2
    offset: "+0530"
  - name: "Open EPG"
    url: "https://www.open-epg.com/files/india3.xml.gz"
    active: true
    priority: 1
    offset: "+0530"
  - name: "Open EPG"
    url: "https://www.open-epg.com/files/india4.xml.gz"
    active: true
    priority: 4
    offset: "+0530"
  - name: "Open EPG"
    url: "https://www.open-epg.com/files/india5.xml.gz"
    active: true
    priority: 5
    offset: "+0530"
  - name: "Open EPG"
    url: "https://www.open-epg.com/files/india6.xml.gz"
    active: true
    priority: 6
    offset: "+0530"
  - name: "Epg Share"
    url: "https://epgshare01.online/epgshare01/epg_ripper_IN1.xml.gz"
    active: true
    priority: 7
    offset: "+0530"
  - name: "Epg Share"
    url: "https://epgshare01.online/epgshare01/epg_ripper_IN2.xml.gz"
    active: true
    priority: 9
    offset: "+0530"
  - name: "Epg Share"
    url: "https://epgshare01.online/epgshare01/epg_ripper_IN4.xml.gz"
    active: true
    priority: 8
    offset: "+0530"

translation:
  enabled: true
  target_lang: "en"
  cache_file: "epg_cache.json"

output_file: "in.tv_epg.xml"
