sources:
  - name: "Open EPG 3"
    url: "https://www.open-epg.com/files/india3.xml.gz"
    active: true
    priority: 1
  - name: "Open EPG 2"
    url: "https://www.open-epg.com/files/india2.xml.gz"
    active: true
    priority: 2
  - name: "Open EPG 1"
    url: "https://www.open-epg.com/files/india1.xml.gz"
    active: true
    priority: 3

output_file: "merged_epg.xml"
