name: EPG Updater

on:
  schedule:
    - cron: '30 21 * * *' # Exactly 03:00 AM IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests PyYAML deep_translator

      - name: Run Script
        id: epg_script
        run: python main.py

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "EPG Update: ${{ steps.epg_script.outputs.total }} channels"
          file_pattern: 'in.tv_epg.xml.gz epg_cache.json'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Indian EPG Update"
          body: "Total Channels: ${{ steps.epg_script.outputs.total }}\nDate: ${{ github.event.head_commit.timestamp }}"
          files: in.tv_epg.xml.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 3 # Only keep the 3 most recent updates
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
